layout_spectrum: 1
typography_spectrum: 0.5972711
color:
  saturation: 0.1863799
  brandStrength: 0.7371369
  lightness: 0.8799283
  rhythmicContrast: 0.9557166
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: alexpinto
